import Foundation
import Testing
@testable import transcript

// MARK: - VideoMetadata

@Suite("VideoMetadata")
struct VideoMetadataTests {

    @Test("url is constructed from videoId")
    func url() {
        let meta = VideoMetadata(
            videoId: "abc123def45",
            title: "T", author: "A",
            publishDate: nil, duration: nil, viewCount: nil,
            description: nil, keywords: []
        )
        #expect(meta.url == "https://www.youtube.com/watch?v=abc123def45")
    }

    @Test("year extracts from publishDate")
    func yearFromDate() {
        let meta = VideoMetadata(
            videoId: "x", title: "T", author: "A",
            publishDate: "2023-07-04", duration: nil, viewCount: nil,
            description: nil, keywords: []
        )
        #expect(meta.year == "2023")
    }

    @Test("year falls back to current year when no publishDate")
    func yearFallback() {
        let meta = VideoMetadata(
            videoId: "x", title: "T", author: "A",
            publishDate: nil, duration: nil, viewCount: nil,
            description: nil, keywords: []
        )
        let formatter = DateFormatter()
        formatter.dateFormat = "yyyy"
        #expect(meta.year == formatter.string(from: Date()))
    }

    @Test("channelURL removes spaces from author")
    func channelURL() {
        let meta = VideoMetadata(
            videoId: "x", title: "T", author: "Cool Channel",
            publishDate: nil, duration: nil, viewCount: nil,
            description: nil, keywords: []
        )
        #expect(meta.channelURL == "https://www.youtube.com/@CoolChannel")
    }
}

// MARK: - CaptionTrack

@Suite("CaptionTrack")
struct CaptionTrackTests {

    @Test("isAutoGenerated when kind is asr")
    func autoGenerated() {
        let track = CaptionTrack(baseUrl: "", languageCode: "en", kind: "asr", name: nil)
        #expect(track.isAutoGenerated)
    }

    @Test("not auto-generated when kind is nil")
    func manualTrack() {
        let track = CaptionTrack(baseUrl: "", languageCode: "en", kind: nil, name: nil)
        #expect(!track.isAutoGenerated)
    }

    @Test("displayName from simpleText")
    func displayNameSimple() {
        let track = CaptionTrack(
            baseUrl: "", languageCode: "en", kind: nil,
            name: TrackName(simpleText: "English", runs: nil)
        )
        #expect(track.displayName == "English")
    }

    @Test("displayName from runs")
    func displayNameRuns() {
        let track = CaptionTrack(
            baseUrl: "", languageCode: "en", kind: nil,
            name: TrackName(simpleText: nil, runs: [
                .init(text: "English"),
                .init(text: " (auto)"),
            ])
        )
        #expect(track.displayName == "English (auto)")
    }

    @Test("displayName falls back to languageCode")
    func displayNameFallback() {
        let track = CaptionTrack(baseUrl: "", languageCode: "fr", kind: nil, name: nil)
        #expect(track.displayName == "fr")
    }
}

// MARK: - VideoDetails

@Suite("VideoDetails")
struct VideoDetailsTests {

    @Test("formats duration with hours")
    func durationWithHours() {
        let details = VideoDetails(
            videoId: "x", title: nil, author: nil, channelId: nil,
            shortDescription: nil, lengthSeconds: "3661", viewCount: nil, keywords: nil
        )
        #expect(details.durationFormatted == "1:01:01")
    }

    @Test("formats duration without hours")
    func durationNoHours() {
        let details = VideoDetails(
            videoId: "x", title: nil, author: nil, channelId: nil,
            shortDescription: nil, lengthSeconds: "125", viewCount: nil, keywords: nil
        )
        #expect(details.durationFormatted == "2:05")
    }

    @Test("nil duration when lengthSeconds is nil")
    func noDuration() {
        let details = VideoDetails(
            videoId: "x", title: nil, author: nil, channelId: nil,
            shortDescription: nil, lengthSeconds: nil, viewCount: nil, keywords: nil
        )
        #expect(details.durationFormatted == nil)
    }
}

// MARK: - JSON3Response.Event

@Suite("JSON3Response.Event")
struct EventTests {

    @Test("text joins segments")
    func textJoinsSegs() {
        let event = JSON3Response.Event(
            tStartMs: 0, dDurationMs: 1000,
            segs: [.init(utf8: "Hello "), .init(utf8: "world")]
        )
        #expect(event.text == "Hello world")
    }

    @Test("text is empty when no segments")
    func textEmptyNoSegs() {
        let event = JSON3Response.Event(tStartMs: 0, dDurationMs: 1000, segs: nil)
        #expect(event.text == "")
    }

    @Test("text skips nil segment values")
    func textSkipsNilSegs() {
        let event = JSON3Response.Event(
            tStartMs: 0, dDurationMs: 1000,
            segs: [.init(utf8: "Hello"), .init(utf8: nil), .init(utf8: " world")]
        )
        #expect(event.text == "Hello world")
    }
}

// MARK: - JSON Decoding

@Suite("Model Decoding")
struct ModelDecodingTests {

    @Test("decodes InnerTubeResponse with captions")
    func decodeResponse() throws {
        let json = """
        {
            "captions": {
                "playerCaptionsTracklistRenderer": {
                    "captionTracks": [
                        {
                            "baseUrl": "https://example.com/caps",
                            "languageCode": "en",
                            "kind": "asr",
                            "name": { "simpleText": "English (auto-generated)" }
                        }
                    ]
                }
            },
            "videoDetails": {
                "videoId": "abc123",
                "title": "Test",
                "author": "Author",
                "lengthSeconds": "300",
                "viewCount": "5000"
            }
        }
        """
        let response = try JSONDecoder().decode(InnerTubeResponse.self, from: json.data(using: .utf8)!)
        let tracks = response.captions?.playerCaptionsTracklistRenderer?.captionTracks
        #expect(tracks?.count == 1)
        #expect(tracks?[0].languageCode == "en")
        #expect(tracks?[0].isAutoGenerated == true)
        #expect(response.videoDetails?.title == "Test")
        #expect(response.videoDetails?.viewCount == "5000")
    }

    @Test("decodes JSON3Response")
    func decodeJSON3() throws {
        let json = """
        {
            "events": [
                {
                    "tStartMs": 500,
                    "dDurationMs": 2000,
                    "segs": [{"utf8": "Hello "}, {"utf8": "world"}]
                }
            ]
        }
        """
        let response = try JSONDecoder().decode(JSON3Response.self, from: json.data(using: .utf8)!)
        #expect(response.events?.count == 1)
        #expect(response.events?[0].text == "Hello world")
        #expect(response.events?[0].tStartMs == 500)
    }
}
