import ArgumentParser
import Foundation

enum OutputFormat: String, CaseIterable, ExpressibleByArgument, Sendable {
    case text
    case srt
    case json
}

enum Formatter {
    static func format(
        _ events: [JSON3Response.Event],
        metadata: VideoMetadata,
        track: CaptionTrack,
        as fmt: OutputFormat
    ) -> String {
        let hdr = header(metadata: metadata, track: track)
        let body: String
        switch fmt {
        case .text: body = formatText(events)
        case .srt: body = formatSRT(events)
        case .json: body = formatJSON(events)
        }
        return hdr + body
    }

    static func header(metadata: VideoMetadata, track: CaptionTrack) -> String {
        formatHeader(metadata: metadata, track: track)
    }

    static func rawText(from events: [JSON3Response.Event]) -> String {
        events
            .compactMap { event -> String? in
                let text = decodeEntities(event.text)
                    .trimmingCharacters(in: .whitespacesAndNewlines)
                return text.isEmpty ? nil : text
            }
            .joined(separator: " ")
    }

    // MARK: - Markdown Header

    private static func formatHeader(metadata: VideoMetadata, track: CaptionTrack) -> String {
        var lines: [String] = []

        lines.append("# \(metadata.title)")
        lines.append("")

        // Metadata table
        lines.append("| | |")
        lines.append("|---|---|")
        lines.append("| **Channel** | \(metadata.author) |")

        if let date = metadata.publishDate {
            lines.append("| **Published** | \(date) |")
        }
        if let duration = metadata.duration {
            lines.append("| **Duration** | \(duration) |")
        }
        if let views = metadata.viewCount, let count = Int(views) {
            let formatted = NumberFormatter.decimal.string(from: NSNumber(value: count)) ?? views
            lines.append("| **Views** | \(formatted) |")
        }

        let displayName = track.displayName
        let alreadyLabeled = displayName.lowercased().contains("auto")
        if alreadyLabeled {
            lines.append("| **Captions** | \(displayName) |")
        } else {
            let kind = track.isAutoGenerated ? "Auto-generated" : "Manual"
            lines.append("| **Captions** | \(displayName) (\(kind)) |")
        }
        lines.append("| **Video** | \(metadata.url) |")

        lines.append("")
        lines.append("---")
        lines.append("")

        return lines.joined(separator: "\n")
    }

    // MARK: - Plain Text

    private static func formatText(_ events: [JSON3Response.Event]) -> String {
        // Merge caption fragments into flowing paragraphs.
        // Use time gaps (>2s between events) to detect paragraph breaks.
        var paragraphs: [String] = []
        var currentParagraph: [String] = []
        var lastEndMs: Int = 0

        for event in events {
            let text = decodeEntities(event.text)
                .trimmingCharacters(in: .whitespacesAndNewlines)
            guard !text.isEmpty else { continue }

            let startMs = event.tStartMs ?? 0
            let durationMs = event.dDurationMs ?? 0
            let gap = startMs - lastEndMs

            // A gap > 2 seconds suggests a topic/speaker change
            if gap > 2000 && !currentParagraph.isEmpty {
                paragraphs.append(joinParagraph(currentParagraph))
                currentParagraph = []
            }

            currentParagraph.append(text)
            lastEndMs = startMs + durationMs
        }

        if !currentParagraph.isEmpty {
            paragraphs.append(joinParagraph(currentParagraph))
        }

        return paragraphs.joined(separator: "\n\n")
    }

    private static func joinParagraph(_ fragments: [String]) -> String {
        var result = ""
        for fragment in fragments {
            if result.isEmpty {
                result = fragment
                continue
            }
            let lastChar = result.last ?? " "
            let firstChar = fragment.first ?? " "
            // If the previous fragment ends mid-word or the next starts lowercase,
            // join with a space. Otherwise use a space too — captions are fragments.
            if lastChar.isLetter && firstChar.isLowercase {
                result += " " + fragment
            } else if lastChar.isPunctuation || lastChar.isWhitespace {
                result += " " + fragment
            } else {
                result += " " + fragment
            }
        }
        return result
    }

    // MARK: - SRT

    private static func formatSRT(_ events: [JSON3Response.Event]) -> String {
        var lines: [String] = []
        var index = 1

        for event in events {
            guard let startMs = event.tStartMs else { continue }
            let text = decodeEntities(event.text)
                .trimmingCharacters(in: .whitespacesAndNewlines)
            guard !text.isEmpty else { continue }

            let durationMs = event.dDurationMs ?? 3000
            let endMs = startMs + durationMs

            lines.append("\(index)")
            lines.append("\(srtTimestamp(startMs)) --> \(srtTimestamp(endMs))")
            lines.append(text)
            lines.append("")
            index += 1
        }

        return lines.joined(separator: "\n")
    }

    private static func srtTimestamp(_ ms: Int) -> String {
        let totalSeconds = ms / 1000
        let hours = totalSeconds / 3600
        let minutes = (totalSeconds % 3600) / 60
        let seconds = totalSeconds % 60
        let millis = ms % 1000
        return String(format: "%02d:%02d:%02d,%03d", hours, minutes, seconds, millis)
    }

    // MARK: - JSON

    private static func formatJSON(_ events: [JSON3Response.Event]) -> String {
        struct Entry: Encodable {
            let start: String
            let durationMs: Int
            let text: String
        }

        let entries = events.compactMap { event -> Entry? in
            guard let startMs = event.tStartMs else { return nil }
            let text = decodeEntities(event.text)
                .trimmingCharacters(in: .whitespacesAndNewlines)
            guard !text.isEmpty else { return nil }

            let totalSeconds = startMs / 1000
            let hours = totalSeconds / 3600
            let minutes = (totalSeconds % 3600) / 60
            let seconds = totalSeconds % 60
            let millis = startMs % 1000
            let timestamp = String(format: "%02d:%02d:%02d.%03d", hours, minutes, seconds, millis)

            return Entry(
                start: timestamp,
                durationMs: event.dDurationMs ?? 3000,
                text: text
            )
        }

        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
        guard let data = try? encoder.encode(entries),
              let json = String(data: data, encoding: .utf8) else {
            return "[]"
        }
        return json
    }

    // MARK: - HTML Entity Decoding

    static func decodeEntities(_ text: String) -> String {
        var result = text
        let entities: [(String, String)] = [
            ("&amp;", "&"),
            ("&lt;", "<"),
            ("&gt;", ">"),
            ("&quot;", "\""),
            ("&#39;", "'"),
            ("&apos;", "'"),
            ("&#x27;", "'"),
            ("&#x2F;", "/"),
            ("&nbsp;", " "),
        ]
        for (entity, replacement) in entities {
            result = result.replacingOccurrences(of: entity, with: replacement)
        }
        // Numeric entities: &#NNN;
        if result.contains("&#") {
            let pattern = /&#(\d+);/
            result = result.replacing(pattern) { match in
                if let code = Int(match.1), let scalar = Unicode.Scalar(code) {
                    return String(Character(scalar))
                }
                return String(match.0)
            }
        }
        return result
    }
}

extension NumberFormatter {
    static let decimal: NumberFormatter = {
        let f = NumberFormatter()
        f.numberStyle = .decimal
        return f
    }()
}
