import Foundation

// MARK: - InnerTube Request

struct InnerTubeRequest: Encodable, Sendable {
    let videoId: String
    let context: Context

    struct Context: Encodable, Sendable {
        let client: Client
    }

    struct Client: Encodable, Sendable {
        let clientName: String
        let clientVersion: String
    }

    static func android(videoId: String) -> InnerTubeRequest {
        InnerTubeRequest(
            videoId: videoId,
            context: Context(
                client: Client(
                    clientName: "ANDROID",
                    clientVersion: "20.10.38"
                )
            )
        )
    }
}

// MARK: - InnerTube Response (partial)

struct InnerTubeResponse: Decodable, Sendable {
    let captions: Captions?
    let videoDetails: VideoDetails?
}

struct VideoDetails: Decodable, Sendable {
    let videoId: String?
    let title: String?
    let author: String?
    let channelId: String?
    let shortDescription: String?
    let lengthSeconds: String?
    let viewCount: String?
    let keywords: [String]?

    var durationFormatted: String? {
        guard let seconds = lengthSeconds.flatMap(Int.init) else { return nil }
        let h = seconds / 3600
        let m = (seconds % 3600) / 60
        let s = seconds % 60
        if h > 0 {
            return String(format: "%d:%02d:%02d", h, m, s)
        }
        return String(format: "%d:%02d", m, s)
    }
}

// MARK: - Video Metadata (combined from multiple sources)

struct VideoMetadata: Sendable {
    let videoId: String
    let title: String
    let author: String
    let publishDate: String?
    let duration: String?
    let viewCount: String?
    let description: String?
    let keywords: [String]

    var url: String {
        "https://www.youtube.com/watch?v=\(videoId)"
    }

    var channelURL: String {
        "https://www.youtube.com/@\(author.replacingOccurrences(of: " ", with: ""))"
    }

    var year: String {
        if let date = publishDate, date.count >= 4 {
            return String(date.prefix(4))
        }
        let formatter = DateFormatter()
        formatter.dateFormat = "yyyy"
        return formatter.string(from: Date())
    }
}

struct Captions: Decodable, Sendable {
    let playerCaptionsTracklistRenderer: TracklistRenderer?
}

struct TracklistRenderer: Decodable, Sendable {
    let captionTracks: [CaptionTrack]?
}

struct CaptionTrack: Decodable, Sendable {
    let baseUrl: String
    let languageCode: String
    let kind: String?
    let name: TrackName?

    var isAutoGenerated: Bool {
        kind == "asr"
    }

    var displayName: String {
        if let text = name?.simpleText {
            return text
        }
        if let runs = name?.runs, !runs.isEmpty {
            return runs.compactMap(\.text).joined()
        }
        return languageCode
    }
}

struct TrackName: Decodable, Sendable {
    let simpleText: String?
    let runs: [Run]?

    struct Run: Decodable, Sendable {
        let text: String?
    }
}

// MARK: - JSON3 Caption Format

struct JSON3Response: Decodable, Sendable {
    let events: [Event]?

    struct Event: Decodable, Sendable {
        let tStartMs: Int?
        let dDurationMs: Int?
        let segs: [Segment]?

        struct Segment: Decodable, Sendable {
            let utf8: String?
        }

        var text: String {
            guard let segs else { return "" }
            return segs.compactMap(\.utf8).joined()
        }
    }
}
