import ArgumentParser
import Foundation

@main
struct Transcript: AsyncParsableCommand {
    static let configuration = CommandConfiguration(
        commandName: "transcript",
        abstract: "Download YouTube video transcripts.",
        version: "1.1.0"
    )

    @Argument(help: "YouTube video URL or video ID.")
    var video: String

    @Option(name: [.short, .long], help: "Output format: text (default), srt, json.")
    var format: OutputFormat = .text

    @Option(name: [.short, .long], help: "Caption language code (default: en).")
    var language: String = "en"

    @Flag(name: .long, help: "List available caption tracks and exit.")
    var list: Bool = false

    @Flag(name: .long, help: "Reformat transcript using AI for readability.")
    var clean: Bool = false

    @Flag(name: .long, help: "Print to stdout only, do not save to file.")
    var noSave: Bool = false

    func run() async throws {
        let videoID = try VideoID(from: video)
        let client = YouTubeClient()

        if list {
            let tracks = try await client.listTracks(videoID: videoID.value)
            printTracks(tracks)
        } else {
            let (metadata, track, events) = try await client.fetchTranscript(
                videoID: videoID.value,
                language: language
            )

            var body = Formatter.format(events, metadata: metadata, track: track, as: format)

            if clean && format == .text {
                FileHandle.standardError.write(Data("Formatting with AI...\n".utf8))
                let rawText = Formatter.rawText(from: events)
                let cleaned = try await AIFormatter.format(rawText, metadata: metadata)
                body = Formatter.header(metadata: metadata, track: track) + cleaned
            }

            let output = body

            if noSave {
                print(output)
            } else {
                let path = try saveTranscript(output, metadata: metadata)
                print("Saved to \(path)")
            }
        }
    }

    private func saveTranscript(_ content: String, metadata: VideoMetadata) throws -> String {
        let home = FileManager.default.homeDirectoryForCurrentUser
        let dir = home
            .appendingPathComponent("Documents/transcripts")
            .appendingPathComponent(metadata.year)

        try FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)

        let safeTitle = sanitizeFilename(metadata.title)
        let ext = format == .json ? "json" : "md"
        let filename = "\(safeTitle).\(ext)"
        let filePath = dir.appendingPathComponent(filename)

        try content.write(to: filePath, atomically: true, encoding: .utf8)
        return filePath.path
    }

    private func sanitizeFilename(_ name: String) -> String {
        let illegal = CharacterSet(charactersIn: "/\\:*?\"<>|")
        var sanitized = name.components(separatedBy: illegal).joined(separator: "-")
        // Collapse multiple dashes/spaces
        sanitized = sanitized.replacingOccurrences(of: "  ", with: " ")
        // Trim to reasonable length
        if sanitized.count > 100 {
            sanitized = String(sanitized.prefix(100))
        }
        return sanitized.trimmingCharacters(in: .whitespacesAndNewlines)
    }

    private func printTracks(_ tracks: [CaptionTrack]) {
        print("Available caption tracks:")
        print(String(repeating: "-", count: 50))
        for track in tracks {
            let kind = track.isAutoGenerated ? "auto" : "manual"
            print("  \(track.languageCode.padding(toLength: 8, withPad: " ", startingAt: 0)) \(track.displayName.padding(toLength: 24, withPad: " ", startingAt: 0)) [\(kind)]")
        }
    }
}
