import Foundation

struct YouTubeClient: Sendable {
    private static let androidUA = "com.google.android.youtube/20.10.38 (Linux; U; Android 12)"
    private static let browserUA = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
    private static let apiKey = "AIzaSyAO_FJ2SlqU8Q4STEHLGCilw_Y9_11qcW8"

    // MARK: - Public

    func listTracks(videoID: String) async throws -> [CaptionTrack] {
        let response = try await fetchPlayerResponse(videoID: videoID)
        guard let tracks = response.captions?.playerCaptionsTracklistRenderer?.captionTracks,
              !tracks.isEmpty else {
            throw TranscriptError.noCaptionsAvailable
        }
        return tracks
    }

    func fetchTranscript(videoID: String, language: String) async throws -> (metadata: VideoMetadata, track: CaptionTrack, events: [JSON3Response.Event]) {
        let response = try await fetchPlayerResponse(videoID: videoID)

        guard let tracks = response.captions?.playerCaptionsTracklistRenderer?.captionTracks,
              !tracks.isEmpty else {
            throw TranscriptError.noCaptionsAvailable
        }

        let track = try selectTrack(from: tracks, language: language)

        // Fetch captions and publish date concurrently
        async let events = downloadCaptions(track: track)
        async let publishDate = fetchPublishDate(videoID: videoID)

        let details = response.videoDetails
        let metadata = VideoMetadata(
            videoId: videoID,
            title: details?.title ?? "Unknown",
            author: details?.author ?? "Unknown",
            publishDate: try? await publishDate,
            duration: details?.durationFormatted,
            viewCount: details?.viewCount,
            description: details?.shortDescription,
            keywords: details?.keywords ?? []
        )

        return (metadata, track, try await events)
    }

    // MARK: - Private

    private func fetchPlayerResponse(videoID: String) async throws -> InnerTubeResponse {
        let url = URL(string: "https://www.youtube.com/youtubei/v1/player?key=\(Self.apiKey)")!
        var request = URLRequest(url: url)
        request.httpMethod = "POST"
        request.setValue("application/json", forHTTPHeaderField: "Content-Type")
        request.setValue(Self.androidUA, forHTTPHeaderField: "User-Agent")

        let body = InnerTubeRequest.android(videoId: videoID)
        request.httpBody = try JSONEncoder().encode(body)

        let data: Data
        do {
            (data, _) = try await URLSession.shared.data(for: request)
        } catch {
            throw TranscriptError.networkError(underlying: error)
        }

        return try JSONDecoder().decode(InnerTubeResponse.self, from: data)
    }

    private func fetchPublishDate(videoID: String) async throws -> String? {
        let url = URL(string: "https://www.youtube.com/watch?v=\(videoID)")!
        var request = URLRequest(url: url)
        request.setValue(Self.browserUA, forHTTPHeaderField: "User-Agent")

        let (data, _) = try await URLSession.shared.data(for: request)
        guard let html = String(data: data, encoding: .utf8) else { return nil }

        let pattern = /"publishDate":"([^"]+)"/
        if let match = html.firstMatch(of: pattern) {
            // Return just the date portion (YYYY-MM-DD) from the ISO timestamp
            let full = String(match.1)
            if let tIndex = full.firstIndex(of: "T") {
                return String(full[..<tIndex])
            }
            return full
        }
        return nil
    }

    private func selectTrack(from tracks: [CaptionTrack], language: String) throws -> CaptionTrack {
        // Exact match
        let exact = tracks.filter { $0.languageCode == language }
        if let manual = exact.first(where: { !$0.isAutoGenerated }) {
            return manual
        }
        if let auto = exact.first {
            return auto
        }

        // Prefix match (e.g., "en" matches "en-US")
        let prefix = tracks.filter { $0.languageCode.hasPrefix(language) }
        if let manual = prefix.first(where: { !$0.isAutoGenerated }) {
            return manual
        }
        if let auto = prefix.first {
            return auto
        }

        throw TranscriptError.languageNotFound(
            requested: language,
            available: tracks.map(\.languageCode)
        )
    }

    private func downloadCaptions(track: CaptionTrack) async throws -> [JSON3Response.Event] {
        // Replace srv3 format with json3 if present, otherwise append
        var urlString = track.baseUrl
        if urlString.contains("fmt=srv3") {
            urlString = urlString.replacingOccurrences(of: "fmt=srv3", with: "fmt=json3")
        } else {
            let separator = urlString.contains("?") ? "&" : "?"
            urlString += "\(separator)fmt=json3"
        }

        guard let url = URL(string: urlString) else {
            throw TranscriptError.captionDownloadFailed
        }

        var request = URLRequest(url: url)
        request.setValue(Self.androidUA, forHTTPHeaderField: "User-Agent")

        let data: Data
        let response: URLResponse
        do {
            (data, response) = try await URLSession.shared.data(for: request)
        } catch {
            throw TranscriptError.networkError(underlying: error)
        }

        guard let http = response as? HTTPURLResponse, http.statusCode == 200, !data.isEmpty else {
            throw TranscriptError.captionDownloadFailed
        }

        let json = try JSONDecoder().decode(JSON3Response.self, from: data)

        guard let events = json.events, !events.isEmpty else {
            throw TranscriptError.noCaptionsAvailable
        }

        return events
    }
}
